== Leaving Sweetness for two weeks on the Coast
=== Retiring carML and coastML at two weeks

*Bottom Line, Up Front*:

. I'm retiring https://github.com/lojikil/carML[carML]; it was an interesting project, but I had made some choices along the way that limited forward momentum
. I've spent the last two weeks working on https://github.com/lojikil/coastML[coastML], a new, small ML dialect, similar to http://mth.github.io/yeti/[Yeti] with some lessons learnt from carML
. coastML is almost at feature parity with carML, and I have some interesting things planned for it

== leaving sweetness and retiring carML

carML has been an interesting project over these last 6 years; I've learnt a lot about writing an ML dialect, and it's been fairly
interesting. Having said that, carML's code has evolved *a lot* over the years, largely due to design changes I had. For example,
originally I was thinking about supporting gradual typing or the like in carML, so complex types like `ref` and `array` didn't
always take a type parameter. I also switched from OCaml style `type of othertype` style declarations to Scala-style `type[othertype]`;
this change meant there was a lot of support for two *completely different types of declaration styles within one code base*. Additionally,
functions originally had very traditional `type1 -> type2 => type3` style declarations, before I realized I really liked a simple
`function[type1 type2 type3]` style much better; it's simpler, it's compact, and it's easy to tell what the intent is. Additionally,
since carML doesn't support currying, the arrow style actually could be confusing as to what is going on.

Sometimes we need to be mature and realize when a project has run it's course, and it's time to move on; this is one of those times for
me personally. However, I really *did* enjoy some things about the language:

. The idea to cut down types from OCaml to Scala and more was great; this allowed for simple parsing & compact design, without changing much of the intent.
.. Consider `(int * int * int)` vs `tuple[int int int]`; they both mean the same thing, but it's very clear what the latter is
. Tools win out; when you're working in your own language, you need tools and output over designs and neat hacks
. Using carML to write carML was great, and I want more of that

== Relaxing on the coast

As the coastML README file mentions, I was working on some Multics ideas a few weeks ago, and wondering if I could make code that was
nicer than Python's `if-elif-else` chains, but without upgrading to Python3.10. I actually played around with generating Python from
carML previously, and so didn't want to dive into that. Instead, I poked around http://coconut-lang.org[Coconut] for a bit, and it was
an intriguing answer: all valid Python is valid Coconut, which just extends the language with ML-isms.

If you know me, you know that I've spent a fair amount of time in my various language designs to generate _human readable code_ from
compilers. This means that the output should be digestible, editable, and honestly near indistinguishable from code a human might write.
Will we employ tricks or otherwise make things efficient? Absolutely, but not at the expense of legibility. This is exactly where
my issue with Coconut came from; when I compiled Coconut code, it definitely resulted in Python code... but not code I would want
to personally use or edit. This is fine if you want to use a language as a compile target, so no judgement there! However, my intent
is often that I want to write in something that is pleasant to _me_ to write in, but deliver it to people who may want to use it
without installing my tools. 

So I ended up, as I often do, thinking about http://mth.github.io/yeti/[Yeti]. Yeti is a **tiny** ML dialect for the JVM, which
elides most syntax in favor of simple constructions and interaction with the host language. I started thinking "oh, if you just added
a `let` to Yeti here, or a `def` there, it would be pretty neat..." and then I paused for a moment. Why *do* we always want to _add_ to
a language? Why not subtract, making things as minimal as possible. So I looked at Yeti, and combined it with a few things from carML,
and sketched out a simple language I initially just called "experimental langauge No. 30:"

[source]
----
foo = fn x y {  # <1>
    # functions are just named bindings
    # there's no other real need for
    # syntax
    case x # <2>
        | 10 { print_endline "ok, x is 10" } # <3>
        | 11 { print_endline "ok, x is 11" }
        | (x >= y) { print_endline "ok, x is >= y" } # <4>
        | _ { print_endline "oh no, x is none of the above" } # <5>
    esac # <6>
}
foo 10 5; <7>
foo 20 5;
----
<1> Functions are just names bound with an `=`
<2> There's no need for `if`, `when`, `match`; just have a simple `case` form
<3> Cases are: a condition and a block. That's it
<4> Guard clauses are just that: clauses
<5> The default case is just `_`, like many languages
<6> End a `case` with the reverse, `esac`
<7> Function calls elide parens or other special syntax; just a `;`

It's small, easily understood, and relatively similar to Yeti, with some of the ideas I've learnt from carML baked in. I'm still working
on the initial bootstrap compiler, but there's enough there that you can access it from Python3 quite nicely:

[source]
----
import carpet
src='a = 10;\nb = 20;\nfoo = fn x y {\n    x + y\n};\nfoo a b;\n'
c = carpet.CarpetPython(src)
c.load()
c.generate()
----

== relax on the coast, stay for a while

I'll be working on adding lots of things to this, namely other langauge targets like C and Golang, as well as adding depth to the 
compiler itself. I'd also like to port libraries I've written in ReasonML, such as https://github.com/lojikil/rosejson[RoseJSON],
and make the ecosystem as friendly as possible. So relax on the coast, stay for while
